mysite/myapp/urls.py
from django.urls import path

from . import views

app_name = "myapp"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:question_id>/", views.detail, name="detail"),
    path("<int:question_id>/results/", views.results, name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
    path("add_question/", views.add_question, name='add_question'),
    path("<int:question_id>/delete_question/", views.delete_question, name='delete_question'),
    path("<int:question_id>/update_question/", views.update_question, name='update_question'),
    path('<int:question_id>/add_answer/', views.add_answer, name='add_answer'),

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("myapp/", include("myapp.urls")),
    path('admin/', admin.site.urls),
]

mysite/myapp/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
 
# Remember the three-step guide to making model changes:
    # Change your models (in models.py).
    # Run python mysite/manage.py makemigrations to create migrations for those changes
    # Run python mysite/manage.py migrate to apply those changes to the database.

class Question(models.Model):
    nickname = models.CharField(max_length=15, default='anonim')
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answer_set', default=1)
    nickname = models.CharField(max_length=15, default='anonim')
    answer_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    def __str__(self):
        return self.answer_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

mysite/myapp/forms.py
from django import forms
from .models import Question, Answer

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['nickname', 'question_text']

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['nickname', 'answer_text']

mysite/myapp/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django import forms
from django.utils import timezone

from .models import Choice, Question, Answer
from .forms import QuestionForm, AnswerForm

def index(request):
    latest_question_list = Question.objects.order_by("-pub_date")
    context = {"latest_question_list": latest_question_list}
    return render(request, "myapp/index.html", context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    answers = question.answer_set.order_by("-pub_date")
    return render(request, "myapp/detail.html", {"question": question, 'answers': answers})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "myapp/results.html", {"question": question})

def add_question(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.pub_date = timezone.now()
            question.save()
    else:
        form = QuestionForm()

    return render(request, 'myapp/add_question.html', {'form': form})

def update_question(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    
    if request.method == 'POST':
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.pub_date = timezone.now()
            question.save()
    else:
        form = QuestionForm(instance=question)

    return render(request, 'myapp/update_question.html', {'form': form})

def delete_question(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
        question.delete()
    return redirect('../../')

def add_answer(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.question = question
            answer.pub_date = timezone.now()
            answer.save()
            return redirect('../')

    else:
        form = AnswerForm()

    return render(request, 'myapp/add_answer.html', {'form': form, 'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "myapp/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("myapp:results", args=(question.id,)))

mysite/myapp/templates/myapp/add_answer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DjangoMidterm</title>
</head>
<body>
    <!DOCTYPE html>
<html>
<head>
    <title>Add Answer</title>
</head>
<body>
    <header>
        Welcome to Ilim's Project!
        <hr>
    </header>

    <h1>Add Answer</h1>
    <p>Question: {{ question.question_text }}</p>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>

    <a href="{% url 'myapp:detail' question.id %}">Back to Question Details</a>
</body>
</html>

</body>
</html>

mysite/myapp/templates/myapp/add_question.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DjangoMidterm</title>
</head>
<body>
    <header>
        Welcome to Ilim's Project!
        <hr>
    </header>

    <h1>Add a Question</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <br>
    <a href="{% url 'myapp:index' %}">Back to Main Page</a>
</body>
</html>

mysite/myapp/templates/myapp/delete_question.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DjangoMidterm</title>
</head>
<body>
    <header>
        Welcome to Ilim's Project!
        <hr>
    </header>

    <a href="{% url 'myapp:index' %}">Back to Main Page</a>
</body>
</html>

mysite/myapp/templates/myapp/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DjangoMidterm</title>
</head>
<body>
    <header>
        Welcome to Ilim's Project!
        <hr>
    </header>

    <form action="{% url 'myapp:vote' question.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend><h1>{{ question.question_text }}</h1></legend>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
        </fieldset>
        <input type="submit" value="Vote">
    </form>

{% comment %}
	  <ul>
	    {% for choice in question.choice_set.all %}
	        <li>{{ choice.choice_text }}</li>
	    {% endfor %}
	    </ul>
{% endcomment %}

    <h2>Answers:</h2>
    <div>
        <a href="{% url 'myapp:add_answer' question.id%}">Add a New Answer</a>
        <br>
    </div>
    <ul>
        {% for answer in answers %}
            <li>{{answer.nickname}}: {{ answer.answer_text }}</li>
        {% endfor %}
    </ul>

    <a href="{% url 'myapp:update_question' question.id %}">Update this question</a>
    <hr>
    <form method="post" action="{% url 'myapp:delete_question' question.id %}">
        {% csrf_token %}
        <button type="submit">Delete</button>
    </form>
    <hr>
    <br>
    <a href="{% url 'myapp:index' %}">Back to Main Page</a>
</body>
</html>

mysite/myapp/templates/myapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DjangoMidterm</title>
</head>
<body>
    <header>
        Welcome to Ilim's Project!
        <hr>
    </header>

    <div>
        <a href="{% url 'myapp:add_question' %}">Add a New Question</a>
        <br>
    </div>

    <div>
    {% if latest_question_list %}
        <ul>
        {% for question in latest_question_list %}
            <li>
                <a href="{% url 'myapp:detail' question.id %}">{{question.nickname}}: {{ question.question_text }}</a>
                <br>{{question.pub_date}}<hr>
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No threads are available.</p>
    {% endif %}
    </div>
</body>
</html>

mysite/myapp/templates/myapp/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DjangoMidterm</title>
</head>
<body>
    <header>
        Welcome to Ilim's Project!
        <hr>
    </header>
    <h1>{{ question.question_text }}</h1>

    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>

    <a href="{% url 'myapp:detail' question.id %}">Vote again?</a>
</body>
</html>

mysite/myapp/templates/myapp/update_question.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DjangoMidterm</title>
</head>
<body>
    <header>
        Welcome to Ilim's Project!
        <hr>
    </header>

    <h1>Update a Question</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update</button>
    </form>

    <a href="{% url 'myapp:index' %}">Back to Main Page</a>
</body>
</html>